kind: pipeline
type: exec
name: Build and Push Docker Image

platform:
  os: linux
  arch: amd64

steps:
- name: Build
  environment:
    QUAY_USERNAME:
      from_secret: QUAY_USERNAME
    QUAY_PASSWORD:
      from_secret: QUAY_PASSWORD
  commands:
    - npm i
    - echo $QUAY_PASSWORD | docker login quay.io --username $QUAY_USERNAME --password-stdin
