services:
  proxy:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: release-aio
      # cache_to: 
      # cache_from: 
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    environment:
      - HOSTNAME=site
      - EMAIL=user@email.com    # required for https
      - STAGING=false           # Set to "true" to use staging
    # volumes:
